name: great_homies
description: A food App made in Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+3
#  firebase_analytics: ^5.0.10
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  firebase_storage: ^3.1.3
  #TODO: Complete Permissions process for IOS
  file_picker: 1.4.3+1
  permission_handler: 4.0.0
#  stepper_touch: 0.0.1
  flare_flutter: 2.0.1
  carousel_slider: 1.4.1
  flutter_rounded_progress_bar: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4
  #Docs for flutter icons: https://github.com/fluttercommunity/flutter_launcher_icons
  #Run the following packages:
  #flutter pub get
  #flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/